- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Get demo-flask source
  git:
    repo: "https://github.com/arnaudmorin/demo-flask.git"
    dest: "/home/ubuntu/demo-flask"

- name: Install python dependencies
  pip:
    name: flask

- name: Set demo-flask service in place
  copy:
    src: files/demo-flask.service
    dest: /etc/systemd/system/demo-flask.service
  become: yes

- name: Start demo-flask
  systemd:
    name: demo-flask
    daemon_reload: yes
    state: restarted
    enabled: True
  become: yes

- name: Generate demo-flask configuration for caddy
  template:
    src: "roles/demo-flask/templates/caddy.conf.tpl"
    dest: "/etc/caddy/caddy.conf.d/demo-flask.conf"
    owner: www-data
    group: www-data
  become: yes

- name: Restart caddy
  systemd:
    name: caddy
    state: restarted
    enabled: True
  become: yes
